### ISSUE TITLE
Valid JSON (129,002 characters) not converted correctly

### ISSUE THREAD

**Issue by skibulk** [konklone/json#42] opened 2014-09-18 12:56 UTC
The following JSON: http://mtgjson.com/json/KTK.json
Validates via: http://jsonformatter.curiousconcept.com/
But only 16 rows of data is converted by your script...

The reason is that the JSON has multiple nested arrays of data. I think some kind of alert notice should be issued so users know that the data is being truncated. Alternatively, the script keep the nested arrays, but leave them as one long csv field.

**Comment by konklone** [comment] 2014-09-22 04:40
You're right, the tool doesn't handle deeply nested JSON well. I'm going to close as a dupe of #34. Also check out one idea for resolving this in #31. This tool isn't under very active development right now, but ideas and pull requests are welcome!

**Closed as completed by konklone** 2014-09-22 04:40 UTC
