### ISSUE TITLE
Handling UTF-8 Characters

### ISSUE THREAD

**Issue by RadiusMWright** [konklone/json#53] opened 2015-03-31 00:01 UTC
There seems to be an issue handing UTF-8 characters, for instance "Reference “Resetting " is converted to "Reference â€œResetting" 

Seems to get caught up on curly quotes and other UTF-8 special characters.

Otherwise I like your app better than others (https://json-csv.com/) - it more logically creates a CSV than alternatives. However, json-csv.com handles UTF-8 special characters...

**Comment by konklone** [comment] 2015-03-31 02:37
Actually, for me, it's even worse -- when I try `{"name": "Reference “Resetting"}` in Chrome or Firefox I cause the whole tab to hang and take up 100% CPU and crash.

It hangs on `JSON.parse()` as best I can tell, but when I run `JSON.parse()` on the string in the Chrome console, it works just fine. I don't know what's up. Any ideas?

**Comment by kylerog** [comment] 2016-07-05 17:49
+1. Fails to properly handle japanese characters during csv download. It does manage to display on screen correctly, however.

**Comment by konklone** [comment] 2016-07-06 00:13
> Actually, for me, it's even worse -- when I try `{"name": "Reference “Resetting"}` in Chrome or Firefox I cause the whole tab to hang and take up 100% CPU and crash.

This works for me now, actually: http://konklone.io/json/?id=a41655b3193a4d3ee472dfb94952c412

> +1. Fails to properly handle japanese characters during csv download. It does manage to display on screen correctly, however.

@rogerskw Can you create a permalink to an example of this?

**Comment by kylerog** [comment] 2016-07-06 03:15
I retract that. Turns out excel was failing to render it. Raw text in atom works fine.

**Comment by konklone** [comment] 2016-07-06 05:35
Awesome! Then I think, since I found that the previous issue isn't reproducible, that this issue is actually all set. Closing.

**Closed as completed by konklone** 2016-07-06 05:35 UTC
