### ISSUE TITLE
Error parsing some specific JSON

### ISSUE THREAD

**Issue by wraysu** [konklone/json#158] opened 2017-06-11 03:06 UTC
I'm having an issue converting this JSON:

```json
[{"id":"1","name":"臺北市","towns":[{"id":"1","name":"中正區","postal":"100"},{"id":"2","name":"大同區","postal":"103"},{"id":"3","name":"中山區","postal":"104"},{"id":"4","name":"松山區","postal":"105"},{"id":"5","name":"大安區","postal":"106"},{"id":"6","name":"萬華區","postal":"108"},{"id":"7","name":"信義區","postal":"110"},{"id":"8","name":"士林區","postal":"111"},{"id":"9","name":"北投區","postal":"112"},{"id":"10","name":"內湖區","postal":"114"},{"id":"11","name":"南港區","postal":"115"},{"id":"12","name":"文山區","postal":"116"}]},{"id":"2","name":"基隆","towns":[{"id":"13","name":"仁愛區","postal":"200"},{"id":"14","name":"信義區","postal":"201"},{"id":"15","name":"中正區","postal":"202"},{"id":"16","name":"中山區","postal":"203"},{"id":"17","name":"安樂區","postal":"204"},{"id":"18","name":"暖暖區","postal":"205"},{"id":"19","name":"七堵區","postal":"206"}]},{"id":"3","name":"新北市","towns":[{"id":"20","name":"萬里區","postal":"207"},{"id":"21","name":"金山區","postal":"208"},{"id":"26","name":"板橋區","postal":"220"},{"id":"27","name":"汐止區","postal":"221"},{"id":"28","name":"深坑區","postal":"222"},{"id":"29","name":"石碇區","postal":"223"},{"id":"30","name":"瑞芳區","postal":"224"},{"id":"31","name":"平溪區","postal":"226"},{"id":"32","name":"雙溪區","postal":"227"},{"id":"33","name":"貢寮區","postal":"228"},{"id":"34","name":"新店區","postal":"231"},{"id":"35","name":"坪林區","postal":"232"},{"id":"36","name":"烏來區","postal":"233"},{"id":"37","name":"永和區","postal":"234"},{"id":"38","name":"中和區","postal":"235"},{"id":"39","name":"土城區","postal":"236"},{"id":"40","name":"三峽區","postal":"237"},{"id":"41","name":"樹林區","postal":"238"},{"id":"42","name":"鶯歌區","postal":"239"},{"id":"43","name":"三重區","postal":"241"},{"id":"44","name":"新莊區","postal":"242"},{"id":"45","name":"泰山區","postal":"243"},{"id":"46","name":"林口區","postal":"244"},{"id":"47","name":"蘆洲區","postal":"247"},{"id":"48","name":"五股區","postal":"248"},{"id":"49","name":"八里區","postal":"249"},{"id":"50","name":"淡水區","postal":"251"},{"id":"51","name":"三芝區","postal":"252"},{"id":"52","name":"石門區","postal":"253"}]},{"id":"4","name":"連江縣","towns":[{"id":"22","name":"南竿鄉","postal":"209"},{"id":"23","name":"北竿鄉","postal":"210"},{"id":"24","name":"莒光鄉","postal":"211"},{"id":"25","name":"東引鄉","postal":"212"}]},{"id":"5","name":"宜蘭縣","towns":[{"id":"53","name":"宜蘭市","postal":"260"},{"id":"54","name":"頭城鎮","postal":"261"},{"id":"55","name":"礁溪鄉","postal":"262"},{"id":"56","name":"壯圍鄉","postal":"263"},{"id":"57","name":"員山鄉","postal":"264"},{"id":"58","name":"羅東鎮","postal":"265"},{"id":"59","name":"三星鄉","postal":"266"},{"id":"60","name":"大同鄉","postal":"267"},{"id":"61","name":"五結鄉","postal":"268"},{"id":"62","name":"冬山鄉","postal":"269"},{"id":"63","name":"蘇澳鎮","postal":"270"},{"id":"64","name":"南澳鄉","postal":"272"}]},{"id":"6","name":"新竹市”,”towns":[{"id":"65","name":"東區","postal":"300"},{"id":"66","name":"香山區","postal":"300"},{"id":"67","name":"北區","postal":"300"}]},{"id":"7","name":"新竹縣”,”towns":[{"id":"68","name":"竹北市","postal":"302"},{"id":"69","name":"湖口鄉","postal":"303"},{"id":"70","name":"新豐鄉","postal":"304"},{"id":"71","name":"新埔鎮","postal":"305"},{"id":"72","name":"關西鎮","postal":"306"},{"id":"73","name":"芎林鄉","postal":"307"},{"id":"74","name":"寶山鄉","postal":"308"},{"id":"75","name":"竹東鎮","postal":"310"},{"id":"76","name":"五峰鄉","postal":"311"},{"id":"77","name":"橫山鄉","postal":"312"},{"id":"78","name":"尖石鄉","postal":"313"},{"id":"79","name":"北埔鄉","postal":"314"},{"id":"80","name":"峨眉鄉","postal":"315"}]},{"id":"8","name":"桃園市","towns":[{"id":"81","name":"中壢區","postal":"320"},{"id":"82","name":"平鎮區","postal":"324"},{"id":"83","name":"龍潭區","postal":"325"},{"id":"84","name":"楊梅區","postal":"326"},{"id":"85","name":"新屋區","postal":"327"},{"id":"86","name":"觀音區","postal":"328"},{"id":"87","name":"桃園區","postal":"330"},{"id":"88","name":"龜山區","postal":"333"},{"id":"89","name":"八德區","postal":"334"},{"id":"90","name":"大溪區","postal":"335"},{"id":"91","name":"復興區","postal":"336"},{"id":"92","name":"大園區","postal":"337"},{"id":"93","name":"蘆竹區","postal":"338"}]},{"id":"9","name":"苗栗","towns":[{"id":"94","name":"竹南鎮","postal":"350"},{"id":"95","name":"頭份鎮","postal":"351"},{"id":"96","name":"三灣鄉","postal":"352"},{"id":"97","name":"南庄鄉","postal":"353"},{"id":"98","name":"獅潭鄉","postal":"354"},{"id":"99","name":"後龍鎮","postal":"356"},{"id":"100","name":"通霄鎮","postal":"357"},{"id":"101","name":"苑裡鎮","postal":"358"},{"id":"102","name":"苗栗市","postal":"360"},{"id":"103","name":"造橋鄉","postal":"361"},{"id":"104","name":"頭屋鄉","postal":"362"},{"id":"105","name":"公館鄉","postal":"363"},{"id":"106","name":"大湖鄉","postal":"364"},{"id":"107","name":"泰安鄉","postal":"365"},{"id":"108","name":"銅鑼鄉","postal":"366"},{"id":"109","name":"三義鄉","postal":"367"},{"id":"110","name":"西湖鄉","postal":"368"},{"id":"111","name":"卓蘭鎮","postal":"369"}]},{"id":"10","name":"臺中市","towns":[{"id":"112","name":"中區","postal":"400"},{"id":"113","name":"東區","postal":"401"},{"id":"114","name":"南區","postal":"402"},{"id":"115","name":"西區","postal":"403"},{"id":"116","name":"北區","postal":"404"},{"id":"117","name":"北屯區","postal":"406"},{"id":"118","name":"西屯區","postal":"407"},{"id":"119","name":"南屯區","postal":"408"},{"id":"120","name":"太平區","postal":"411"},{"id":"121","name":"大里區","postal":"412"},{"id":"122","name":"霧峰區","postal":"413"},{"id":"123","name":"烏日區","postal":"414"},{"id":"124","name":"豐原區","postal":"420"},{"id":"125","name":"后里區","postal":"421"},{"id":"126","name":"石岡區","postal":"422"},{"id":"127","name":"東勢區","postal":"423"},{"id":"128","name":"和平區","postal":"424"},{"id":"129","name":"新社區","postal":"426"},{"id":"130","name":"潭子區","postal":"427"},{"id":"131","name":"大雅區","postal":"428"},{"id":"132","name":"神岡區","postal":"429"},{"id":"133","name":"大肚區","postal":"432"},{"id":"134","name":"沙鹿區","postal":"433"},{"id":"135","name":"龍井區","postal":"434"},{"id":"136","name":"梧棲區","postal":"435"},{"id":"137","name":"清水區","postal":"436"},{"id":"138","name":"大甲區","postal":"437"},{"id":"139","name":"外埔區","postal":"438"},{"id":"140","name":"大安區","postal":"439"}]},{"id":"11","name":"彰化縣","towns":[{"id":"141","name":"彰化市","postal":"500"},{"id":"142","name":"芬園鄉","postal":"502"},{"id":"143","name":"花壇鄉","postal":"503"},{"id":"144","name":"秀水鄉","postal":"504"},{"id":"145","name":"鹿港鎮","postal":"505"},{"id":"146","name":"福興鄉","postal":"506"},{"id":"147","name":"線西鄉","postal":"507"},{"id":"148","name":"和美鎮","postal":"508"},{"id":"149","name":"伸港鄉","postal":"509"},{"id":"150","name":"員林鎮","postal":"510"},{"id":"151","name":"社頭鄉","postal":"511"},{"id":"152","name":"永靖鄉","postal":"512"},{"id":"153","name":"埔心鄉","postal":"513"},{"id":"154","name":"溪湖鎮","postal":"514"},{"id":"155","name":"大村鄉","postal":"515"},{"id":"156","name":"埔鹽鄉","postal":"516"},{"id":"157","name":"田中鎮","postal":"520"},{"id":"158","name":"北斗鎮","postal":"521"},{"id":"159","name":"田尾鄉","postal":"522"},{"id":"160","name":"埤頭鄉","postal":"523"},{"id":"161","name":"溪州鄉","postal":"524"},{"id":"162","name":"竹塘鄉","postal":"525"},{"id":"163","name":"二林鎮","postal":"526"},{"id":"164","name":"大城鄉","postal":"527"},{"id":"165","name":"芳苑鄉","postal":"528"},{"id":"166","name":"二水鄉","postal":"530"}]},{"id":"12","name":"南投縣","towns":[{"id":"167","name":"南投市","postal":"540"},{"id":"168","name":"中寮鄉","postal":"541"},{"id":"169","name":"草屯鎮","postal":"542"},{"id":"170","name":"國姓鄉","postal":"544"},{"id":"171","name":"埔里鎮","postal":"545"},{"id":"172","name":"仁愛鄉","postal":"546"},{"id":"173","name":"名間鄉","postal":"551"},{"id":"174","name":"集集鎮","postal":"552"},{"id":"175","name":"水里鄉","postal":"553"},{"id":"176","name":"魚池鄉","postal":"555"},{"id":"177","name":"信義鄉","postal":"556"},{"id":"178","name":"竹山鎮","postal":"557"},{"id":"179","name":"鹿谷鄉","postal":"558"}]},{"id":"13","name":"嘉義市”,”towns":[{"id":"180","name":"西區","postal":"600"},{"id":"181","name":"東區","postal":"600"}]},{"id":"14","name":"嘉義縣”,”towns":[{"id":"182","name":"番路鄉","postal":"602"},{"id":"183","name":"梅山鄉","postal":"603"},{"id":"184","name":"竹崎鄉","postal":"604"},{"id":"185","name":"阿里山鄉","postal":"605"},{"id":"186","name":"中埔鄉","postal":"606"},{"id":"187","name":"大埔鄉","postal":"607"},{"id":"188","name":"水上鄉","postal":"608"},{"id":"189","name":"鹿草鄉","postal":"611"},{"id":"190","name":"太保市","postal":"612"},{"id":"191","name":"朴子市","postal":"613"},{"id":"192","name":"東石鄉","postal":"614"},{"id":"193","name":"六腳鄉","postal":"615"},{"id":"194","name":"新港鄉","postal":"616"},{"id":"195","name":"民雄鄉","postal":"621"},{"id":"196","name":"大林鎮","postal":"622"},{"id":"197","name":"溪口鄉","postal":"623"},{"id":"198","name":"義竹鄉","postal":"624"},{"id":"199","name":"布袋鎮","postal":"625"}]},{"id":"15","name":"雲林縣","towns":[{"id":"200","name":"斗南鎮","postal":"630"},{"id":"201","name":"大埤鄉","postal":"631"},{"id":"202","name":"虎尾鎮","postal":"632"},{"id":"203","name":"土庫鎮","postal":"633"},{"id":"204","name":"褒忠鄉","postal":"634"},{"id":"205","name":"東勢鄉","postal":"635"},{"id":"206","name":"臺西鄉","postal":"636"},{"id":"207","name":"崙背鄉","postal":"637"},{"id":"208","name":"麥寮鄉","postal":"638"},{"id":"209","name":"斗六市","postal":"640"},{"id":"210","name":"林內鄉","postal":"643"},{"id":"211","name":"古坑鄉","postal":"646"},{"id":"212","name":"莿桐鄉","postal":"647"},{"id":"213","name":"西螺鎮","postal":"648"},{"id":"214","name":"二崙鄉","postal":"649"},{"id":"215","name":"北港鎮","postal":"651"},{"id":"216","name":"水林鄉","postal":"652"},{"id":"217","name":"口湖鄉","postal":"653"},{"id":"218","name":"四湖鄉","postal":"654"},{"id":"219","name":"元長鄉","postal":"655"}]},{"id":"16","name":"臺南市","towns":[{"id":"220","name":"中西區","postal":"700"},{"id":"221","name":"東區","postal":"701"},{"id":"222","name":"南區","postal":"702"},{"id":"223","name":"北區","postal":"704"},{"id":"224","name":"安平區","postal":"708"},{"id":"225","name":"安南區","postal":"709"},{"id":"226","name":"永康區","postal":"710"},{"id":"227","name":"歸仁區","postal":"711"},{"id":"228","name":"新化區","postal":"712"},{"id":"229","name":"左鎮區","postal":"713"},{"id":"230","name":"玉井區","postal":"714"},{"id":"231","name":"楠西區","postal":"715"},{"id":"232","name":"南化區","postal":"716"},{"id":"233","name":"仁德區","postal":"717"},{"id":"234","name":"關廟區","postal":"718"},{"id":"235","name":"龍崎區","postal":"719"},{"id":"236","name":"官田區","postal":"720"},{"id":"237","name":"麻豆區","postal":"721"},{"id":"238","name":"佳里區","postal":"722"},{"id":"239","name":"西港區","postal":"723"},{"id":"240","name":"七股區","postal":"724"},{"id":"241","name":"將軍區","postal":"725"},{"id":"242","name":"學甲區","postal":"726"},{"id":"243","name":"北門區","postal":"727"},{"id":"244","name":"新營區","postal":"730"},{"id":"245","name":"後壁區","postal":"731"},{"id":"246","name":"白河區","postal":"732"},{"id":"247","name":"東山區","postal":"733"},{"id":"248","name":"六甲區","postal":"734"},{"id":"249","name":"下營區","postal":"735"},{"id":"250","name":"柳營區","postal":"736"},{"id":"251","name":"鹽水區","postal":"737"},{"id":"252","name":"善化區","postal":"741"},{"id":"253","name":"大內區","postal":"742"},{"id":"254","name":"山上區","postal":"743"},{"id":"255","name":"新市區","postal":"744"},{"id":"256","name":"安定區","postal":"745"}]},{"id":"17","name":"高雄市","towns":[{"id":"257","name":"新興區","postal":"800"},{"id":"258","name":"前金區","postal":"801"},{"id":"259","name":"苓雅區","postal":"802"},{"id":"260","name":"鹽埕區","postal":"803"},{"id":"261","name":"鼓山區","postal":"804"},{"id":"262","name":"旗津區","postal":"805"},{"id":"263","name":"前鎮區","postal":"806"},{"id":"264","name":"三民區","postal":"807"},{"id":"265","name":"楠梓區","postal":"811"},{"id":"266","name":"小港區","postal":"812"},{"id":"267","name":"左營區","postal":"813"},{"id":"268","name":"仁武區","postal":"814"},{"id":"269","name":"大社區","postal":"815"},{"id":"270","name":"岡山區","postal":"820"},{"id":"271","name":"路竹區","postal":"821"},{"id":"272","name":"阿蓮區","postal":"822"},{"id":"273","name":"田寮區","postal":"823"},{"id":"274","name":"燕巢區","postal":"824"},{"id":"275","name":"橋頭區","postal":"825"},{"id":"276","name":"梓官區","postal":"826"},{"id":"277","name":"彌陀區","postal":"827"},{"id":"278","name":"永安區","postal":"828"},{"id":"279","name":"湖內區","postal":"829"},{"id":"280","name":"鳳山區","postal":"830"},{"id":"281","name":"大寮區","postal":"831"},{"id":"282","name":"林園區","postal":"832"},{"id":"283","name":"鳥松區","postal":"833"},{"id":"284","name":"大樹區","postal":"840"},{"id":"285","name":"旗山區","postal":"842"},{"id":"286","name":"美濃區","postal":"843"},{"id":"287","name":"六龜區","postal":"844"},{"id":"288","name":"內門區","postal":"845"},{"id":"289","name":"杉林區","postal":"846"},{"id":"290","name":"甲仙區","postal":"847"},{"id":"291","name":"桃源區","postal":"848"},{"id":"292","name":"那瑪夏區","postal":"849"},{"id":"293","name":"茂林區","postal":"851"},{"id":"294","name":"茄萣區","postal":"852"}]},{"id":"18","name":"澎湖縣","towns":[{"id":"295","name":"馬公市","postal":"880"},{"id":"296","name":"西嶼鄉","postal":"881"},{"id":"297","name":"望安鄉","postal":"882"},{"id":"298","name":"七美鄉","postal":"883"},{"id":"299","name":"白沙鄉","postal":"884"},{"id":"300","name":"湖西鄉","postal":"885"}]},{"id":"19","name":"金門縣","towns":[{"id":"301","name":"金沙鎮","postal":"890"},{"id":"302","name":"金湖鎮","postal":"891"},{"id":"303","name":"金寧鄉","postal":"892"},{"id":"304","name":"金城鎮","postal":"893"},{"id":"305","name":"烈嶼鄉","postal":"894"},{"id":"306","name":"烏坵鄉","postal":"896"}]},{"id":"20","name":"屏東縣","towns":[{"id":"307","name":"屏東市","postal":"900"},{"id":"308","name":"三地門鄉","postal":"901"},{"id":"309","name":"霧臺鄉","postal":"902"},{"id":"310","name":"瑪家鄉","postal":"903"},{"id":"311","name":"九如鄉","postal":"904"},{"id":"312","name":"里港鄉","postal":"905"},{"id":"313","name":"高樹鄉","postal":"906"},{"id":"314","name":"鹽埔鄉","postal":"907"},{"id":"315","name":"長治鄉","postal":"908"},{"id":"316","name":"麟洛鄉","postal":"909"},{"id":"317","name":"竹田鄉","postal":"911"},{"id":"318","name":"內埔鄉","postal":"912"},{"id":"319","name":"萬丹鄉","postal":"913"},{"id":"320","name":"潮州鎮","postal":"920"},{"id":"321","name":"泰武鄉","postal":"921"},{"id":"322","name":"來義鄉","postal":"922"},{"id":"323","name":"萬巒鄉","postal":"923"},{"id":"324","name":"崁頂鄉","postal":"924"},{"id":"325","name":"新埤鄉","postal":"925"},{"id":"326","name":"南州鄉","postal":"926"},{"id":"327","name":"林邊鄉","postal":"927"},{"id":"328","name":"東港鎮","postal":"928"},{"id":"329","name":"琉球鄉","postal":"929"},{"id":"330","name":"佳冬鄉","postal":"931"},{"id":"331","name":"新園鄉","postal":"932"},{"id":"332","name":"枋寮鄉","postal":"940"},{"id":"333","name":"枋山鄉","postal":"941"},{"id":"334","name":"春日鄉","postal":"942"},{"id":"335","name":"獅子鄉","postal":"943"},{"id":"336","name":"車城鄉","postal":"944"},{"id":"337","name":"牡丹鄉","postal":"945"},{"id":"338","name":"恆春鎮","postal":"946"},{"id":"339","name":"滿州鄉","postal":"947"}]},{"id":"21","name":"臺東縣","towns":[{"id":"340","name":"臺東市","postal":"950"},{"id":"341","name":"綠島鄉","postal":"951"},{"id":"342","name":"蘭嶼鄉","postal":"952"},{"id":"343","name":"延平鄉","postal":"953"},{"id":"344","name":"卑南鄉","postal":"954"},{"id":"345","name":"鹿野鄉","postal":"955"},{"id":"346","name":"關山鎮","postal":"956"},{"id":"347","name":"海端鄉","postal":"957"},{"id":"348","name":"池上鄉","postal":"958"},{"id":"349","name":"東河鄉","postal":"959"},{"id":"350","name":"成功鎮","postal":"961"},{"id":"351","name":"長濱鄉","postal":"962"},{"id":"352","name":"太麻里鄉","postal":"963"},{"id":"353","name":"金峰鄉","postal":"964"},{"id":"354","name":"大武鄉","postal":"965"},{"id":"355","name":"達仁鄉","postal":"966"}]},{"id":"22","name":"花蓮縣","towns":[{"id":"356","name":"花蓮市","postal":"970"},{"id":"357","name":"新城鄉","postal":"971"},{"id":"358","name":"秀林鄉","postal":"972"},{"id":"359","name":"吉安鄉","postal":"973"},{"id":"360","name":"壽豐鄉","postal":"974"},{"id":"361","name":"鳳林鎮","postal":"975"},{"id":"362","name":"光復鄉","postal":"976"},{"id":"363","name":"豐濱鄉","postal":"977"},{"id":"364","name":"瑞穗鄉","postal":"978"},{"id":"365","name":"萬榮鄉","postal":"979"},{"id":"366","name":"玉里鎮","postal":"981"},{"id":"367","name":"卓溪鄉","postal":"982"},{"id":"368","name":"富里鄉","postal":"983"}]}]
```

**Comment by konklone** [comment] 2017-06-11 21:01
The issue is the presence of smart quotes (`”`) in the JSON. The first one appears mid-way in, at character 2751. You'll want to replace them all with regular quotes.

**Comment by konklone** [comment] 2017-06-11 21:07
I'm going to add an automatic fix for this instead.

**Closed as completed** 2017-06-11 21:08 UTC
